config/routes.rb
Rails.application.routes.draw do
  resources :books
  devise_for :users
  root "pages#home"
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :authenticate_user!

  def index
    @books = current_user.books
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = current_user.books.build
  end

  def create
    @book = current_user.books.create(book_params)
    if @book.save
      flash[:notice] = "You have successfully created a book"
      redirect_to books_path
    else
      flash[:error] = "There was a problem with creating your book"
      render 'new'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :comment, :author)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/index.html.erb
<h1>Your Books</h1>
<%= link_to "Create a new book", new_book_path %><br>
<% @books.each do |book| %>
  <%= link_to book.title, book_path(book) %>
  <br>
<% end %>

app/views/books/new.html.erb
<h1>Create a New Book</h1>
<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :author %>
  <%= f.text_field :author %><br>
  <%= f.label :comment %>
  <%= f.text_area :comment %><br>
  <%= f.submit %>
<% end %>

app/views/books/show.html.erb
<h1>Book Details</h1>
Title: <%= @book.title %>
<br>
Author: <%= @book.author %>
<br>
Comment: <%= @book.comment %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookkeeper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= link_to "Books", books_path %>

  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  <% else %>
    <%= link_to('Login', new_user_session_path)  %>  
  <% end %>

  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to the Book Keeper</h1>